spring:
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: backend
  datasource:
    url: jdbc:postgresql://localhost:5432/boardinghouse
    username: boardinghouse
    password: devpassword